name: Renovate Config Validator

on:
  pull_request:
    paths:
      - ".github/renovate.json5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    name: Validate renovate config
    runs-on: ubuntu-latest
    permissions:
      contents: read # to check out code
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Validate renovate config
        uses: suzuki-shunsuke/github-action-renovate-config-validator@1e1604219a6b38ae9a10aff42a28a3656322c31a # v2.4.1
        with:
          config_file_path: .github/renovate.json5
